### ISSUE TITLE
Plug in crashes every few minutes

### ISSUE THREAD

**Issue by willz06jw** [Rall3n/galaxy-integration-amazon#21]
The Amazon plug in crashes every few minutes.  I am new to posting issues, so please let me know what I can give you to help.  

I am running: 
Windows 10 x64 v21H1
GOG Galaxy version 2.0.41.150 - Beta
Plugin version 0.4.1

I have tried reinstalling the plug in, and disconnecting reconnection, to no avail

**Comment by Rall3n** [comment]
Hello @willz06jw,

could you please upload the latest logfile regarding the Amazon plugin? You can find it under `C:\ProgramData\GOG.com\Galaxy\logs\` with the filename `plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log`.

**Comment by willz06jw** [comment]
[plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log](https://github.com/Rall3n/galaxy-integration-amazon/files/7177866/plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log)

**Comment by Rall3n** [comment]
@willz06jw, I couldn't find any trace of anything that would cause a crash of the plugin.
There is an unhandled exception, but as far as I can see it is harmless and should not cause a crash.

Could you tell me what exactly is crashing: the plugin or the client itself? Could you also provide more information on this crash in general?

**Comment by willz06jw** [comment]
It is the plugin itself that crashes.  Here is what I see when it does
<img width="731" alt="PlugInHasCrashed" src="https://user-images.githubusercontent.com/8368005/133930999-34f6490d-f1b9-4a73-93f7-efc5d50c810c.png">

Then I press retry and it acts like it is connected for 3 or so minutes, then crashes again
<img width="736" alt="Connected" src="https://user-images.githubusercontent.com/8368005/133931025-ae34c28f-8170-475f-b84c-984f77fefa73.png">

Here is the log file again.  I noticed that when the crash occurs, the log file "modified date" does not change.  I don't think it writes to the log when it crashes.
[plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log](https://github.com/Rall3n/galaxy-integration-amazon/files/7192249/plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log)

**Comment by Rall3n** [comment]
@willz06jw Sorry for replying this late.

Do you still encounter this error?

The latest log still does not give any hints to why it crashes.

**Comment by willz06jw** [comment]
Yes I still see this error.  I have thousands of games, and 279 from Amazon.  I'm not sure if that has anything to do with it.

**Comment by willz06jw** [comment]
Do you think it is because I have over 256 games?

**Comment by Rall3n** [comment]
> Do you think it is because I have over 256 games?

Doubtful, as I have around 310 games in my Amazon Games library, and it does not crash.

**Comment by willz06jw** [comment]
How about this log, does it help with anything?  See line 11745

[GalaxyClient.log](https://github.com/Rall3n/galaxy-integration-amazon/files/7296372/GalaxyClient.log)

**Comment by willz06jw** [comment]
Just let me know if I can help with anything on this

**Comment by Rall3n** [comment]
@willz06jw I just published a new version which should get rid of the error inside the plugin logfiles.

Regarding the actual issue: I would like you to try with the new version first to see if this was the real problem. If this should not work then I would suggest you try it with only the Amazon plugin.

**Comment by willz06jw** [comment]
Well, it was a pain, but I disconnected all plugins, then removed their files from the "installed" directory.  Then I reinstalled the Amazon plugin from Github, but it is still crashing.  I am attaching the logs
[GalaxyClientService.log](https://github.com/Rall3n/galaxy-integration-amazon/files/7550201/GalaxyClientService.log)
[plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log](https://github.com/Rall3n/galaxy-integration-amazon/files/7550206/plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log)
:

**Comment by Rall3n** [comment]
@willz06jw there is one last thing I would like you to try. This would require you to edit the plugins files by yourself.

I would like you to comment out the lines 180 and 181 in the file `plugin.py`. They should not affect functionality of the plugin based on your log files.

If this still does not solve your issue I would suggest trying to report it to GOG (`Cog wheel top left` >> `Report issue`) and add a link to this GitHub issue.

**Comment by jedthe3rd** [comment]
@Rall3n I am getting this issue as well. Same issue where there isn't any error logs for the crash. But I did observe GOG saying plugin not responding then the plugin was marked as crashed. Maybe there is an API timeout that it is expecting to be refreshed? 

After observing it more windows definitely doesn't detect it as not responding in task manager so it looks like GOG Galaxy itself is killing it.

**Comment by Rall3n** [comment]
@jedthe3rd Would you mind providing the log files for both the plugin and Galaxy in general?

**Comment by jedthe3rd** [comment]
Looks like the plugin isn't responding to the heartbeat check:

``` log
2022-08-14 12:45:31.586 [Information][ (0)] [TID 2086196][galaxy_client]: Finished sending presence heartbeat.
2022-08-14 12:45:47.121 [Error][ (0)] [TID 28720][galaxy_client]: Plugin - pluginID/amazon_c2cd2e29-8b02-35a9-86fc-3faf90255857 is not responding.
2022-08-14 12:45:47.121 [Information][ (0)] [TID 28720][galaxy_client]: Request to stop plugin pluginID/amazon_c2cd2e29-8b02-35a9-86fc-3faf90255857
2022-08-14 12:45:48.207 [Information][ (0)] [TID 28720][galaxy_client]: Received onPluginShutdownFailure for plugin 'pluginID/amazon_c2cd2e29-8b02-35a9-86fc-3faf90255857'.
2022-08-14 12:45:48.207 [Warning][ (0)] [TID 28720][galaxy_client]: Plugin 'pluginID/amazon_c2cd2e29-8b02-35a9-86fc-3faf90255857' shutdown failed, killing process
2022-08-14 12:45:48.308 [Error][ (0)] [TID 28720][galaxy_client]: Plugin - pluginID/amazon_c2cd2e29-8b02-35a9-86fc-3faf90255857 has crashed.
```

[plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log](https://github.com/Rall3n/galaxy-integration-amazon/files/9333924/plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log)
[GalaxyClient.log](https://github.com/Rall3n/galaxy-integration-amazon/files/9333925/GalaxyClient.log)
